### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by Legolaszstudio** [ValentinChirikov/magic-lantern-1000D#1]
Wondering if you ever got this working on a 1000d?

Sadly I don't have the necessary experience, skill and time to build it myself, so would you be so kind to provide me with the final zip file, so I can play around with it too?

Thanks :)

**Comment by ValentinChirikov** [comment]
> Wondering if you ever got this working on a 1000d?
> 
> Sadly I don't have the necessary experience, skill and time to build it myself, so would you be so kind to provide me with the final zip file, so I can play around with it too?
> 
> Thanks :)

Hello ) i've tried, but have not succeed, sorry.
